#!/bin/bash
# extracts strings from *.py and .ui files and
# generates a gettext .pot template.

dirname=${PWD##*/}
pot_name=./po/$dirname.pot

if [ ! -d ./po ]; then
	mkdir ./po
fi
if [ -f $pot_name ]; then
	rm $pot_name
fi

# generate string headers of all glade files
for f in *.ui ; do
	intltool-extract --type=gettext/glade $f
done

# write template files
xgettext *.py *.h --keyword=_ --keyword=N_ --from-code=UTF-8 --output=$pot_name

#clean up
rm *.h
