#!/bin/bash
LIB_DIR=./Mailnag

cd $(dirname $(readlink -f $0))

if [ $# -eq 0 ] || [ $1 == "--quiet" ] || [ $1 == "-q" ]; then
	python2 $LIB_DIR/mailnag.py $@ &
else 
	python2 $LIB_DIR/mailnag.py $@
fi
