#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# mailnag-config
#
# Copyright 2011 - 2016 Patrick Ulbrich <zulu99@gmx.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('GLib', '2.0')

import os
import subprocess
from gi.repository import Gtk, Gio

from Mailnag.common.utils import fix_cwd

fix_cwd()

from Mailnag.common.i18n import _
from Mailnag.common.utils import set_procname, shutdown_existing_instance, get_data_file, get_data_paths
from Mailnag.common.dist_cfg import BIN_DIR, PACKAGE_NAME
from Mailnag.configuration.configwindow import ConfigWindow


class App(Gtk.Application):
	def __init__(self):
		Gtk.Application.__init__(self, application_id = 'com.github.pulp.Mailnag')
		self.win = None


	def do_startup(self):
		Gtk.Application.do_startup(self)
		
		# Add icons in alternative data paths (e.g. ./data/icons) 
		# to the icon search path in case Mailnag is launched 
		# from a local directory (without installing).
		icon_theme = Gtk.IconTheme.get_default()
		for path in get_data_paths():
			icon_theme.append_search_path(os.path.join(path, "icons"))

		builder = Gtk.Builder()
		builder.set_translation_domain(PACKAGE_NAME)
		builder.add_from_file(get_data_file("appmenu.ui"))
		self.set_app_menu(builder.get_object("appmenu"))
		
		about_action = Gio.SimpleAction.new("about", None)
		about_action.connect("activate", self.about_cb)
		self.add_action(about_action)
		
		quit_action = Gio.SimpleAction.new("quit", None)
		quit_action.connect("activate", self.quit_cb)
		self.add_action(quit_action)
	
	
	def do_activate(self):
		Gtk.Application.do_activate(self)
		
		if not self.win:
			self.win = ConfigWindow(self)
		self.win.get_gtk_window().present()
	
	
	def do_shutdown(self):
		Gtk.Application.do_shutdown(self)
		
		if self.win.get_daemon_enabled():
			try:
				# the launched daemon shuts down 
				# an already running daemon
				print "Launching Mailnag daemon."
				subprocess.Popen(os.path.join(BIN_DIR, "mailnag"))
			except:
				print "ERROR: Failed to launch Mailnag daemon."
		else:
			# shutdown running Mailnag daemon
			shutdown_existing_instance(wait_for_completion = False)
	
	
	def about_cb(self, action, parameter):
		aboutdialog = Gtk.AboutDialog()
		aboutdialog.set_title(_("About %s") % PACKAGE_NAME.title())
		aboutdialog.set_program_name(PACKAGE_NAME.title())
		aboutdialog.set_copyright(_("Copyright (c) 2011 - 2016 Patrick Ulbrich and contributors."))
		aboutdialog.set_logo_icon_name("mailnag")
		aboutdialog.set_website("https://github.com/pulb/mailnag")
		aboutdialog.set_website_label(_("Homepage"))
		aboutdialog.set_license_type(Gtk.License.GPL_2_0)		
		aboutdialog.set_authors([ "Patrick Ulbrich <zulu99@gmx.net>" ])
		aboutdialog.connect("response", lambda w, r: aboutdialog.destroy())
		aboutdialog.set_transient_for(self.win.get_gtk_window())
		aboutdialog.show()

	
	def quit_cb(self, action, parameter):
		self.win.get_gtk_window().close()

	
def main():
	set_procname("mailnag-config")

	app = App()
	app.run(None)


if __name__ == "__main__":  main()
