#!/bin/bash
CONFIG_HOME=$XDG_CONFIG_HOME
if [ "$CONFIG_HOME" == "" ]; then
	CONFIG_HOME="$HOME/.config"
fi
config_dir="$CONFIG_HOME/mailnag"

if [ ! -d "$config_dir" ]; then
	mkdir --parents "$config_dir"
fi
if [ -f "$config_dir/mailnag_config.log" ]; then
	rm "$config_dir/mailnag_config.log"
fi

cd `dirname $0`

python mailnag_config.py >> "$config_dir/mailnag_config.log" 2>&1

if [ $? -eq 0 ]; then
	# Restart mailnag.py
	if [ -f "$config_dir/mailnag.pid" ]; then
		kill $(cat "$config_dir/mailnag.pid")
	fi
	if [ -f "$config_dir/mailnag.log" ]; then
		rm "$config_dir/mailnag.log"
	fi
	python mailnag.py >> "$config_dir/mailnag.log" 2>&1 &
else
	echo mailnag-config discarded
fi
