post_install() {
	gtk-update-icon-cache --quiet /usr/share/icons/hicolor
	
	echo 'To configure Mailnag run mailnag-config.'
}

post_upgrade() {
	gtk-update-icon-cache --quiet /usr/share/icons/hicolor
	
	echo 'IMPORTANT NOTE: As of version 1.0 the format of the config file has changed.'
	echo 'It is recommended to move or delete ~/.config/mailnag/mailnag.cfg'
}

post_remove() {
	gtk-update-icon-cache --quiet /usr/share/icons/hicolor
}
