#!/bin/bash
LIB_DIR=./Mailnag

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/mailnag"

mkdir --parents "$config_dir"

if [ -f "$config_dir/mailnag.pid" ]; then
	kill $(cat "$config_dir/mailnag.pid") 2> /dev/null
fi

rm --force "$config_dir/mailnag.log"

cd $(dirname $(readlink -f $0))
python $LIB_DIR/mailnag.py >> "$config_dir/mailnag.log" 2>&1 &

