#!/bin/bash
LIB_DIR=./Mailnag

CONFIG_HOME=$XDG_CONFIG_HOME
if [ "$CONFIG_HOME" == "" ]; then
	CONFIG_HOME="$HOME/.config"
fi
config_dir="$CONFIG_HOME/mailnag"

main()
{
	if [ -f "$config_dir/mailnag.log" ]; then
		rm "$config_dir/mailnag.log"
	fi
	
	cd $(dirname $(readlink -f $0))
	python $LIB_DIR/mailnag.py >> "$config_dir/mailnag.log" 2>&1 &
}

check_connection()
{
	retries=50
	while ! ping -c1 www.google.com 2>/dev/null 1>&2 && [ $retries -gt 0 ] ; do
		sleep 5
		# ((retries--))
	done
	
	if [ $retries -gt 0 ]; then
		return 0
	else
		return 1 # timed out
	fi
}

if check_connection; then
	main
else
	echo "Error: No internet connection."
fi
