.TH MAILNAG-CONFIG "1" "Feb 2015" "Mailnag 1.1.0"
.SH NAME
mailnag-config \- Mailnag setup utility
.SH SYNOPSIS
\fBmailnag-config\fP
.SH DESCRIPTION
\fBmailnag-config\fP is a utility that makes it easy to setup Mailnag
initially. This only needs to be run once; after running it and closing the
configuration window, Mailnag will be started automatically.
.SH SEE ALSO
.PP
\fBmailnag\fP(1)
.SH AUTHOR
\fBmailnag\fP was written by Patrick Ulbrich <zulu99@gmx.net>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
