.TH MAILNAG "1" "Mar 2016" "Mailnag 1.2.1"
.SH NAME
mailnag \- an extensible mail notification daemon
.SH SYNOPSIS
\fBmailnag\fP
.SH DESCRIPTION
\fBmailnag\fP is a daemon program that checks POP3 and IMAP servers for new mail.
On mail arrival it performs various actions provided by plugins.
It comes with a set of desktop-independent default plugins for
visual/sound notifications, script execution etc. and can be extended
with additional plugins easily.
.PP
Note that you must first run \fBmailnag-config\fR to setup Mailnag.
.SH SEE ALSO
.PP
\fBmailnag-config\fP(1)
.SH AUTHOR
\fBmailnag\fP was written by Patrick Ulbrich <zulu99@gmx.net>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
