.TH MAILNAG "1" "November 2012" "Mailnag 0.5.0"
.SH NAME
mailnag \- a mail notification daemon for GNOME 3
.SH SYNOPSIS
\fBmailnag\fP
.SH DESCRIPTION
\fBmailnag\fP checks POP3 and IMAP servers for new mail. When it finds new
messages, it creates a GNOME 3 notification (integrated with the Shell) that
mentions sender and subject.
.PP
Note that you must first run \fBmailnag_config\fR to setup Mailnag.
.SH SEE ALSO
.PP
\fBmailnag_config\fP(1)
.SH AUTHOR
\fBmailnag\fP was written by Patrick Ulbrich <zulu99@gmx.net>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
